EHealth/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url,include


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^svasth/', include('Svasth.urls' , namespace='Svasth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root =  settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Svasth/urls.py
from django.conf.urls import url

from . import views

app_name = "Svasth"

urlpatterns = [
    url(r'^$', views.index, name='Index'),
    url(r'^(?P<UserID>[0-9]+)/MyDoctors/', views.MyDocters, name="MyDoctors"),
    url(r'^LogIn/', views.LogIn, name='LogIn'),
    url(r'^SignIn/', views.SignIn, name='SignIn'),
    url(r'^(?P<UserID>[0-9]+)/Reports/', views.Reports, name='Reports'),
    url(r'^(?P<UserID>[0-9]+)/Home/', views.home, name='Home'),
    url(r'^(?P<UserID>[0-9]+)/Appointments/', views.Appointments, name='Appointments'),
    url(r'^(?P<UserID>[0-9]+)/Hospital/', views.Hospitals, name='Hospitals'),
    url(r'^(?P<UserID>[0-9]+)/Specialisations/(?P<HopId>[0-9]+)$', views.Special, name='Special'),
    url(r'^(?P<UserID>[0-9]+)/DoctorsSpecial/(?P<SpecId>[0-9]+)$', views.DoctersSpecial, name='DoctoresSpecial'),
    url(r'^Contact/',views.Contacts, name='Contact'),
]

Svasth/models.py
from django.utils.timezone import now
from django.contrib.auth.models import AbstractUser, UserManager as AbstractUserManager
from django.db import models


class User(models.Model):
    User_Id = models.AutoField(primary_key=True)
    User_Name = models.CharField(max_length=100)
    User_Email = models.EmailField(max_length=254)
    User_Password = models.CharField(max_length=255)
    User_BirthDate = models.DateField(blank=True, null=True)
    User_BloodGroup = models.CharField(max_length=4, blank=True, null=True)
    User_Icon = models.FileField(blank=True, null=True)

    def __str__(self):
        return self.User_Name


class Hospital(models.Model):
    Hospital_Id = models.AutoField(primary_key=True)
    Hospital_Name = models.CharField(max_length=254)
    Hospital_Location = models.TextField(max_length=1000)
    Hospital_Contact = models.CharField(max_length=15)
    Hospital_Logo = models.FileField()

    def __str__(self):
        return self.Hospital_Name


class Specialisation(models.Model):
    Specialisation_Id = models.AutoField(primary_key=True)
    Specialisation_Name = models.CharField(max_length=1000)
    Specialisation_Hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)

    def __str__(self):
        return self.Specialisation_Name + "-" + self.Specialisation_Hospital.Hospital_Name


class Doctor(models.Model):
    Doctors_Id = models.AutoField(primary_key=True)
    Doctors_Name = models.CharField(max_length=254)
    Specialisation_Choices = (
        (" Allergist", " Allergist"),
        (" Anesthesiologist", " Anesthesiologist"),
        (" Cardiologist", "Cardiologist "),
        (" Orthopaedic", " Orthopaedic"),
        (" Endocrinologist", " Endocrinologist"),
        (" Dermatologist", " Dermatologist")
    )
    Doctors_Specialisation = models.ForeignKey(Specialisation, on_delete=models.CASCADE)
    Doctors_Icon = models.FileField()
    Doctors_Hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)

    def __str__(self):
        return self.Doctors_Name + " (" + self.Doctors_Specialisation.Specialisation_Name + " )" + "-" + self.Doctors_Hospital.Hospital_Name


class Event(models.Model):
    Event_Id = models.AutoField(primary_key=True)
    Event_Name = models.CharField(max_length=1000)
    Event_Desc = models.TextField(max_length=1000)
    Event_link = models.CharField(max_length=1000)
    Event_img = models.FileField()
    Event_Date = models.DateField(default=now)

    def __str__(self):
        return self.Event_Name


class Report(models.Model):
    Report_Id = models.AutoField(primary_key=True)
    Reports_Choices = (
        (" CT Scan ", " CT Scan "),
        (" Blood Report ", " Blood Report "),
        (" ECG ", " ECG "),
        (" Urine Report ", " Urine Report "),
        (" X-Ray Report ", " X-Ray Report "),
        (" UltraSound Report ", " UltraSound Report ")
    )
    Report_Name = models.CharField(max_length=200, choices=Reports_Choices)
    Report_Desc = models.CharField(max_length=500, default='', blank=True)
    Report_Doc = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    Report_Date = models.DateField(default=now)
    Report_file = models.FileField()
    Report_User = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.Report_User.User_Name + "-" + self.Report_Name


class LoginTime(models.Model):
    LoginTime_Id = models.AutoField(primary_key=True)
    LoginTime_User = models.ForeignKey(User, on_delete=models.CASCADE)
    LoginTime_DateTime = models.DateTimeField()

    def __str__(self):
        return self.LoginTime_User.User_Name


class Appointment(models.Model):
    Appointment_Id = models.AutoField(primary_key=True)
    Appointment_Date = models.DateField()
    Appointment_Time = models.TimeField()
    Appointment_Doc = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    Appointment_User = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.Appointment_User.User_Name


class Relationship(models.Model):
    Relationships_Id = models.AutoField(primary_key=True)
    Relationships_Date = models.DateField()
    Relationships_Doc = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    Relationships_User = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.Relationships_Doc.Doctors_Name + '-' + self.Relationships_User.User_Name


class Contact(models.Model):
    Contact_ID = models.AutoField(primary_key=True)
    Contact_DateTime = models.DateTimeField()
    Contact_Name = models.CharField(max_length=255)
    Contact_Email = models.EmailField()
    Contact_Message = models.TextField(max_length=1000)
    Contact_User = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.Contact_Name + "-" + self.Contact_Email

Svasth/views.py
from .models import User, Doctor, Hospital, Report, LoginTime, Event, Appointment, Specialisation, Relationship, Contact
from django.shortcuts import render, redirect
import datetime
from django.contrib import messages
from passlib.apps import custom_app_context as pwd_context

today = datetime.date.today()
now = datetime.datetime.now()


def Check(x):
    return bool(x == True)


def index(resquest):
    All_Doctors = Doctor.objects.all()
    All_Event = Event.objects.all()
    context = {'All_Doctors': All_Doctors, 'All_Event': All_Event}
    return render(resquest, 'Svasth/Index.html', context)


def home(resquest, UserID):
    ActiveUser = User.objects.get(User_Id=UserID)
    All_Event = Event.objects.all()
    context = {'All_Event': All_Event, 'ActiveUser': ActiveUser, 'UserID': UserID}
    return render(resquest, 'Svasth/Home.html', context)


def MyDocters(resquest, UserID):
    global flag2
    flag2 = True
    if resquest.method == 'POST':
        date = resquest.POST['appointment_date']
        time = resquest.POST['appointment_time']
        doc = resquest.POST['Doc']
        if Appointment.objects.filter(Appointment_Date=date, Appointment_Time=time,
                                      Appointment_User__User_Id=UserID).exists():
            flag2 = False
            messages.error(resquest,"Appointment Couldn't Be Book.")
            return redirect('Svasth:MyDoctors',UserID=UserID)
        if Check(flag2):
            main = Appointment.objects.create(Appointment_Date=date, Appointment_Time=time, Appointment_User_id=UserID,
                                              Appointment_Doc_id=doc)
            main.save()
        return redirect("Svasth:Home")
    All_Relationships = Relationship.objects.filter(Relationships_User__User_Id=UserID)
    Docs = Doctor.objects.all()
    Specs = Specialisation.objects.all()
    All_Doctors = Doctor.objects.all()
    context = {'All_Doctors': All_Doctors, 'Docs': Docs, 'Specs': Specs, 'All_Relationships': All_Relationships,
               'UserID': UserID}
    return render(resquest, 'Svasth/MyDoctors.html', context)


def LogIn(resquest):
    if resquest.method == "POST":
        User_Mail = resquest.POST['email']
        User_Password = resquest.POST['password']

        if User.objects.filter(User_Email=User_Mail).exists():
            UserEmail = User.objects.get(User_Email=User_Mail)
            if pwd_context.verify(User_Password, UserEmail.User_Password):
                log = LoginTime.objects.create(LoginTime_User=UserEmail, LoginTime_DateTime=now)
                log.save()
                UserID = UserEmail.User_Id
                return redirect("Svasth:Home", UserID=UserID)
            else:
                messages.error(resquest, 'Invalid Password')
                return redirect("Svasth:LogIn")

        else:
            messages.error(resquest, 'Invalid Username')
            return redirect("Svasth:LogIn")

    return render(resquest, 'Svasth/LoginPage.html')


def Reports(resquest, UserID):
    All_Reports = Report.objects.filter(Report_User__User_Id=UserID)
    context = {'All_Reports': All_Reports, 'UserID': UserID}
    return render(resquest, 'Svasth/Reports.html', context)


def SignIn(resquest):
    if resquest.method == 'POST':
        Name = resquest.POST['name']
        Email = resquest.POST['email']
        Password = resquest.POST['password']
        PasswordHash = pwd_context.hash(Password)
        Null = None
        if User.objects.filter(User_Email=Email).exists():
            messages.error(resquest, 'Following Email Exist')
            return redirect("Svasth:SignIn")
        else:
            Main = User.objects.create(User_Name=Name, User_Email=Email, User_Password=PasswordHash)
            Main.save()
            UserIDsign = User.objects.get(User_Email=Email)
            return redirect("Svasth:Home", UserID=UserIDsign.User_Id)

    return render(resquest, 'Svasth/SignInPage.html')


def Appointments(resquest, UserID):
    global flag1
    flag1 = True

    if resquest.method == 'POST':
        date = resquest.POST['appointment_date']
        time = resquest.POST['appointment_time']
        doc = resquest.POST['Doc']
        if Appointment.objects.filter(Appointment_Date=date, Appointment_Time=time,
                                      Appointment_User__User_Id=UserID).exists():
            flag1 = False
            messages.error(resquest, "Appointment Couldn't Be Book")
            return redirect("Svasth:Appointments",UserID=UserID)
        if Check(flag1):
            main = Appointment.objects.create(Appointment_Date=date, Appointment_Time=time, Appointment_User_id=UserID,
                                              Appointment_Doc_id=doc)
            main.save()
        # Appointment.objects.filter(Appointment_Id=delete).delete()
        return redirect("Svasth:Appointments",UserID=UserID)

    Apps = Appointment.objects.filter(Appointment_User__User_Id=UserID)
    Docs = Doctor.objects.all()
    Specs = Specialisation.objects.all()
    context = {'Apps': Apps, 'today': today, 'Docs': Docs, 'Specs': Specs, 'UserID': UserID}
    return render(resquest, 'Svasth/Appointments.html', context)


def Hospitals(resquest, UserID):
    Hosps = Hospital.objects.all()
    context = {'Hosps': Hosps, 'UserID': UserID}
    return render(resquest, 'Svasth/Hospital.html', context)


def Special(resquest, HopId, UserID):
    Specs = Specialisation.objects.filter(Specialisation_Hospital__Hospital_Id=HopId)
    context = {'Specs': Specs, 'HopId': HopId, 'UserID': UserID}
    return render(resquest, 'Svasth/Specialisations.html', context)


def DoctersSpecial(resquest, SpecId, UserID):
    global flag
    flag = True
    if resquest.method == 'POST':
        date = resquest.POST['appointment_date']
        time = resquest.POST['appointment_time']
        doc = resquest.POST['Doc']

        if Appointment.objects.filter(Appointment_Date=date,Appointment_Time=time,Appointment_User__User_Id=UserID).exists():
            flag = True
            messages.error(resquest, "Appointment Couldn't Be Book")
            return redirect('Svasth:DoctoresSpecial',SpecId=SpecId,UserID=UserID)
        if Check(flag):
            main = Appointment.objects.create(Appointment_Date=date, Appointment_Time=time, Appointment_User_id=UserID,
                                              Appointment_Doc_id=doc)
            main.save()
        return redirect("Svasth:Home", UserID=UserID)
    Docs = Doctor.objects.filter(Doctors_Specialisation_id=SpecId)
    Specs = Specialisation.objects.all()
    All_Doctors = Doctor.objects.all()
    context = {'All_Doctors': All_Doctors, 'Docs': Docs, 'Specs': Specs, 'UserID': UserID}
    return render(resquest, 'Svasth/DoctorsSpecial.html', context)


def Contacts(resquest):
    if resquest.method == 'POST':
        fname = resquest.POST['fname']
        lname = resquest.POST['lname']
        email = resquest.POST['email']
        message = resquest.POST['message']

        name = fname + ' ' + lname
        if User.objects.filter(User_Email=email).exists():
            UserMade = User.objects.get(User_Email=email)
            con = Contact.objects.create(Contact_DateTime=now, Contact_Email=email, Contact_Message=message,
                                         Contact_Name=name, Contact_User_id=UserMade.User_Id)
            con.save()
        else:
            con = Contact.objects.create(Contact_DateTime=now, Contact_Email=email, Contact_Message=message,
                                         Contact_Name=name)
            con.save()

    return render(resquest, 'Svasth/contact.html')

Svasth/templates/Svasth/Appointments.html
{% load static %}
    <meta charset="UTF-8">
    <title>Svasth</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300, 400, 700" rel="stylesheet"/>

    <link rel="stylesheet" href="{% static 'Svasth/css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'Svasth/css/animate.css' %}"/>
    <link rel="stylesheet" href="{% static 'Svasth/css/owl.carousel.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'Svasth/css/bootstrap-datepicker.css' %}"/>
    <link rel="stylesheet" href="{% static 'Svasth/css/jquery.timepicker.css' %}"/>

    <link rel="stylesheet" href="{% static 'Svasth/fonts/ionicons/css/ionicons.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'Svasth/fonts/fontawesome/css/font-awesome.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'Svasth/fonts/flaticon/font/flaticon.css' %}"/>


    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static 'Svasth/css/style.css' %}">


<header role="banner">
      <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
         <div class="container">
          <a class="navbar-brand" href="index.html">Svasth<span>+</span>  </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarsExample05">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Svasth:Home' UserID %}">News & Events</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href={% url 'Svasth:MyDoctors' UserID%}>My Doctors</a>
              </li>
                <li class = 'nav-item'>
                    <a class="nav-link" href="{% url 'Svasth:Hospitals' UserID %}">Hospitals</a>
                </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Svasth:Reports' UserID %}">My Reports</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'Svasth:Appointments' UserID %}">Appointments</a>
              </li>
              <li class="nav-item">
              <a class="nav-link" href="{% url 'Svasth:Index' %}">Log Out</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

	<section class="home-slider inner-page owl-carousel">
      <div class="slider-item" style="background-image: url('{% static 'Svasth/img/antibiotics.jpg' %}');">

        <div class="container">
          <div class="row slider-text align-items-center">
            <div class="col-md-7 col-sm-12 element-animate">
              <h1>Appointments</h1>
              <p></p>
            </div>
          </div>
        </div>
    </div>
    </section>



  <div class="main">
<br>
<div class="row justify-content-center mb-5 element-animate">
          <div class="col-md-8 text-center mb-5">
            <h2 class="text-uppercase heading border-bottom mb-4">PREVIOUS</h2>
          </div>


      <div class="table-responsive"><center>
      <table class="table " style="width: 70%; border-radius: 10px; align-self: center;">
        <thead style="color: #32597A">
          <tr>
      <th scope="col">#</th>
      <th scope="col">Doctor</th>
      <th scope="col">Specialization</th>
      <th scope="col">Hospital</th>
      <th scope="col">Date</th>
      <th scope="col">Time</th>
    </tr>
        </thead>
{%  csrf_token %}
{% for App in Apps %}
    {% if App.Appointment_Date < today %}
         <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ App.Appointment_Doc.Doctors_Name }}</td>
      <td>{{ App.Appointment_Doc.Doctors_Specialisation.Specialisation_Name }}</td>
      <td>{{ App.Appointment_Doc.Doctors_Hospital.Hospital_Name }}</td>
      <td>{{ App.Appointment_Date }}</td>
      <td>{{ App.Appointment_Time }}</td>
    </tr>
    {% endif %}
{% endfor %}
      </table></center></div></div>
      <br>
      <div class="row justify-content-center mb-5 element-animate">
          <div class="col-md-8 text-center mb-5">
            <h2 class="text-uppercase heading border-bottom mb-4">SCHEDULED</h2>

          </div>
           <div class="table-responsive"><center>
      <table class="table " style="width: 70%; border-radius: 10px; align-self: center;">
        <thead style="color: #32597A">
          <tr>
      <th scope="col">#</th>
      <th scope="col">Doctor</th>
      <th scope="col">Specialization</th>
      <th scope="col">Hospital</th>
      <th scope="col">Date</th>
      <th scope="col">Time</th>
    </tr>
        </thead>

{% for App in Apps %}

    {% if App.Appointment_Date > today %}
         <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ App.Appointment_Doc.Doctors_Name }}</td>
      <td>{{ App.Appointment_Doc.Doctors_Specialisation.Specialisation_Name }}</td>
      <td>{{ App.Appointment_Doc.Doctors_Hospital.Hospital_Name }}</td>
      <td>{{ App.Appointment_Date }}</td>
      <td>{{ App.Appointment_Time }}</td>
    </tr>
    {% endif %}

{% endfor %}
      {% for message in messages %}

                    <div class="alert alert-success" style="background-color: white;border-color: white">
                        <p class="alert-warning" style="background-color: #FFFFFF">{{ message }} </p>
                    </div>
{% endfor %}

      </table></center></div>
        </div>
  </div>


 <a href="#" class="cta-link element-animate" data-aniamte-effect="fadeIn" data-toggle="modal" data-target="#modalAppointment">
     <span class="heading">Make an Appointment</span>
    </a>



<footer class="site-footer" role="contentinfo">
      <div class="container">
        <div class="row mb-5 element-animate">
          <div class="col-md-3 mb-5">
            <h3>Services</h3>
            <ul class="footer-link list-unstyled">
              <li><a href="{% url 'Svasth:Hospitals' UserID %}">Find a doctor</a></li>

              <li><a href="#">Online Services</a></li>
            </ul>
          </div>
          <div class="col-md-3 mb-5">
            <h3>Latest News</h3>
            <ul class="footer-link list-unstyled">
              <li><a href="#">News &amp; Events</a></li>

            </ul>
          </div>
          <div class="col-md-3 mb-5">
            <h3>About</h3>
            <ul class="footer-link list-unstyled">

              <li><a href="#">Feedback</a></li>
            </ul>
          </div>
          <div class="col-md-3 mb-5">
            <h3>Location &amp; Contact</h3>
            <p class="mb-5">CHRIST(Deemed to be University)</p>

            <h4 class="text-uppercase mb-3 h6 text-white">Email</h4>
            <p class="mb-5"><a href="mailto:info@yourdomain.com">info@svasth.com</a></p>

            <h4 class="text-uppercase mb-3 h6 text-white">Phone</h4>
            <p>+91 64 435 3533</p>

          </div>
        </div>

        <div class="row pt-md-3 element-animate">
          <div class="col-md-12">
            <hr class="border-t">
          </div>

          <div class="col-md-6 col-sm-12 text-md-right text-sm-left">
            <a href="#" class="p-2"><span class="fa fa-facebook"></span></a>
            <a href="#" class="p-2"><span class="fa fa-twitter"></span></a>
            <a href="#" class="p-2"><span class="fa fa-instagram"></span></a>
          </div>
        </div>
      </div>
    </footer>

    <!-- Modal -->
    <div class="modal fade" id="modalAppointment" tabindex="-1" role="dialog" aria-labelledby="modalAppointmentLabel" aria-hidden="true">
    {% csrf_token %}
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="modalAppointmentLabel">Svasth<span>+</span> </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form action="#" method="post">
{% csrf_token %}
              <div class="form-group">
                <label  class="text-black">Full Name</label>
                <input type="text" class="form-control" name="appointment_name">
              </div>
              <div class="form-group">
                <label  class="text-black">Email</label>
                <input type="text" class="form-control" name="appointment_email">
              </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                           <label class="text-black">Specialisation</label>
                            <select name="Doc">
{% for Doc in Docs %}
                                <option   value="{{ Doc.Doctors_Id }}">{{ Doc.Doctors_Name }} - {{ Doc.Doctors_Specialisation.Specialisation_Name }}</option>
{% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="text-black">Students</label>
{% for stud in Docs %}

{% endfor %}

                    <input type="checkbox" class="form-control" name="" value="Present">
                  </div>
                </div>

              <div class="form-group">
                <input type="submit" value="Sumbit" class="btn btn-primary">
              </div>
            </form>
          </div>

        </div>
      </div>
    </div>

    <script src="{%  static 'Svasth/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{%  static 'Svasth/js/popper.min.js' %}"></script>
    <script src="{%  static 'Svasth/js/bootstrap.min.js' %}"></script>
    <script src="{%  static 'Svasth/js/owl.carousel.min.js' %}"></script>
    <script src="{%  static 'Svasth/js/bootstrap-datepicker.js' %}"></script>
    <script src="{%  static 'Svasth/js/jquery.timepicker.min.js' %}"></script>
    <script src="{%  static 'Svasth/js/jquery.waypoints.min.js' %}"></script>
    <script src="{%  static 'Svasth/js/main.js' %}"></script>

Svasth/templates/Svasth/LoginPage.html
{% load static %}
<meta charset="utf-8">
<title>Svasth</title>
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
<meta name="format-detection" content="telephone=no">
<meta name="description" content="Page description">
<!--Twitter Card data-->
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@publisher_handle">
<meta name="twitter:title" content="Page Title">
<meta name="twitter:description" content="Page description less than 200 characters">
<meta name="twitter:creator" content="@author_handle">
<meta name="twitter:image" content="http://www.example.com/image.jpg">
<!--Open Graph data-->
<meta property="og:title" content="Title Here">
<meta property="og:type" content="article">
<meta property="og:url" content="http://www.example.com/">
<meta property="og:image" content="http://example.com/image.jpg">
<meta property="og:description" content="Description Here">
<meta property="og:site_name" content="Site Name, i.e. Moz">
<meta property="fb:admins" content="Facebook numeric ID">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'Svasth/img/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'Svasth/img/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'Svasth/img/favicon-16x16.png' %}">
<link rel="mask-icon" href="{% static 'Svasth/img/safari-pinned-tab.svg' %}" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
<link href="https://fonts.googleapis.com/css?family=Karla:400,700&amp;display=swap" rel="stylesheet">
<link rel="stylesheet" media="all" href='{% static 'Svasth/css/styleLogin.css' %}'>

<div class="page page_login" style="background-image: {% static 'Svasth/img/timepass12.jpg' %}">
    <form class="form" action="" method="post" autocomplete="off">
        {% csrf_token %}
        <div class="form__container">
            <div class="logo">
                <img class="logo__pic" src="{% static 'Svasth/img/logo.svg' %}" width="45" alt="#"/>
            </div>
            <div class="fieldset">
                <div class="field"><input class="input" type="email" name="email" placeholder="E-mail address" required>
                </div>
                <div class="field"><input class="input" type="password" name="password" placeholder="Password" required>
                </div>
            </div>
            <button class="btn" name="submit">Sign in</button>
        <br><br>
            {% for message in messages %}

                    <div class="alert alert-success">
                        <p class="alert-warning">{{ message }} </p>
                    </div>
{% endfor %}

            <div class="text">Can’t remember your password? <a href="#">Recover it</a>
            </div>
        </div>
        <div class="form__footer">Don't Have an Account? <a href="{% url 'Svasth:SignIn' %}">Create it</a>
        </div>
    </form>
</div>